import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function DealsPage(){
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)redirect('/login');
 const {data:members}=await s.from('organization_members').select('organization_id').eq('user_id',user.id); const ids=(members??[]).map((m:any)=>m.organization_id);
 let deals:any[]=[]; if(ids.length){ const {data}=await s.from('deals').select('id,status,target_close_date,created_at,updated_at,opportunities(slug,assets(title,currency,asking_price)),buyer_organization_id,seller_organization_id').or(`organization_id.in.(${ids.join(',')}),buyer_organization_id.in.(${ids.join(',')}),seller_organization_id.in.(${ids.join(',')})`).order('updated_at',{ascending:false}); deals=data??[]; }
 return <main className="app-shell"><header className="app-header"><a className="brand" href="/">ASSETVEYRA</a><nav><a href="/workspace">Workspace</a><a href="/opportunities">Marketplace</a></nav></header><section className="page-head"><div className="eyebrow">DEAL EXECUTION</div><h1>From offer to closing.</h1><p>Execution state is explicit: NDA, data room, diligence, offer, negotiation, approval, contract, signing and closing.</p></section><section className="panel"><div className="table">{deals.map((d:any)=><div className="row" key={d.id}><strong>{d.opportunities?.assets?.title||'Deal'}</strong><span>{d.status}</span><span>{d.target_close_date||'Close date pending'}</span><span>{d.opportunities?.assets?.asking_price?`${d.opportunities.assets.currency||''} ${Number(d.opportunities.assets.asking_price).toLocaleString()}`:'—'}</span></div>)}{!deals.length&&<div className="empty-state"><strong>No live deals.</strong><span>Accepted offers and transaction records will appear here.</span></div>}</div></section></main>;
}
