'use client';

import { createContext, createElement, ReactNode, useContext, useEffect, useState, type ElementType } from 'react';
import { normalizeLocale, RTL_LOCALES, translate, type Locale } from '@/lib/i18n';
import { translateEnumValue } from '@/lib/i18nEnums';
import '@/lib/workspaceTranslations';

const LocaleContext = createContext<Locale>('en');
export function useLocale(): Locale { return useContext(LocaleContext); }
export function I18nText({ id, as = 'span' }: { id: string; as?: ElementType }) { const locale=useLocale(); const translated=translate(id,locale); return createElement(as,null,translated===id?translateEnumValue(id,locale):translated); }
const ARABIC_LAYOUT_CSS=`html.rtl body{direction:rtl;text-align:right}html.rtl .site-header,html.rtl .app-header,html.rtl .hero-home,html.rtl .market-strip,html.rtl .section,html.rtl .workflow-section,html.rtl .wide-heading,html.rtl .market-toolbar,html.rtl .market-grid,html.rtl .opportunity-grid,html.rtl .market-card,html.rtl .opportunity-card,html.rtl .capability-grid,html.rtl .lifecycle,html.rtl .intelligence-section,html.rtl .contact-section,html.rtl .footer,html.rtl .dashboard-head,html.rtl .page-head,html.rtl .form-page,html.rtl .detail,html.rtl .stats,html.rtl .facts,html.rtl .row,html.rtl .form-grid,html.rtl .auth-page{direction:rtl}html.rtl .hero-copy-block,html.rtl .market-card,html.rtl .opportunity-card,html.rtl .contact-card,html.rtl .auth-card{text-align:right}.rtl .hero-copy-block{order:1}.rtl .hero-visual{order:2}.rtl .hero-location{left:auto;right:24px}.rtl .hero-floating-card{right:auto;left:24px}.rtl .market-strip>div{border-right:0;border-left:1px solid var(--line)}.rtl .market-strip>div:last-child{border-left:0}.rtl .lifecycle{border-left:0;border-right:1px solid var(--line)}.rtl .lifecycle-step{border-right:0;border-left:1px solid var(--line)}.rtl .lifecycle-step:last-child{border-left:0}.rtl .source-badge{left:auto;right:15px}.rtl .market-index{right:auto;left:15px}.rtl .stats div{border-right:0;border-left:1px solid var(--line)}.rtl .stats div:last-child{border-left:0}.rtl .facts div{padding:20px 0 20px 16px}`;
export default function LocaleShell({children,initialLocale}:{children:ReactNode;initialLocale:Locale}){const [locale,setLocale]=useState<Locale>(initialLocale);useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=RTL_LOCALES.has(locale)?'rtl':'ltr';document.documentElement.dataset.locale=locale;document.documentElement.classList.toggle('rtl',RTL_LOCALES.has(locale));document.cookie=`assetveyra-locale=${locale}; Max-Age=31536000; Path=/; SameSite=Lax`;const selects=document.querySelectorAll<HTMLSelectElement>('[data-language-menu]');selects.forEach(select=>{select.value=locale;select.onchange=()=>setLocale(normalizeLocale(select.value));});const outside=(event:MouseEvent)=>{const target=event.target;if(!(target instanceof Node))return;document.querySelectorAll<HTMLDetailsElement>('details.av-menu[open]').forEach(menu=>{if(!menu.contains(target))menu.removeAttribute('open');});};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')document.querySelectorAll<HTMLDetailsElement>('details.av-menu[open]').forEach(menu=>menu.removeAttribute('open'));};document.addEventListener('click',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',outside);document.removeEventListener('keydown',escape);selects.forEach(select=>{select.onchange=null;});};},[locale]);return <LocaleContext.Provider value={locale}><style id="assetveyra-arabic-layout">{ARABIC_LAYOUT_CSS}</style>{children}</LocaleContext.Provider>}
