'use client';

import { useLocale } from '@/components/LocaleShell';
import type { Locale } from '@/lib/i18n';

type Copy = { eyebrow: string; title: string; updated: string; intro: string; sections: { title: string; body: string[]; bullets?: string[] }[]; notice: string };

const COPY: Record<Locale, Copy> = {
  en: {
    eyebrow: 'TRANSACTION AGREEMENT', title: 'Transaction Service & 1% Fee Agreement', updated: 'Effective date: 16 September 2026',
    intro: 'This template records the commercial relationship between AssetVeyra and a client using AssetVeyra to identify, negotiate and coordinate a real-estate transaction. A transaction-specific agreement may supplement or replace these terms where required by applicable law.',
    sections: [
      { title: '1. Scope of AssetVeyra services', body: ['AssetVeyra may receive and prepare the client request, search and match opportunities, communicate with owners and buyers, transmit offers and counteroffers, facilitate commercial negotiations, coordinate transaction steps, coordinate access to legal and other professional providers, and coordinate practical travel arrangements where required by the transaction.'] },
      { title: '2. Final price and decision', body: ['AssetVeyra may negotiate and facilitate a mutually acceptable commercial outcome, but the buyer and seller remain the parties who approve the final price and contractual terms. AssetVeyra does not have authority to bind either party unless a separate written authority expressly provides otherwise.'] },
      { title: '3. AssetVeyra fee — 1%', body: ['The standard AssetVeyra transaction service fee is 1% of the final agreed transaction value for a transaction successfully completed through AssetVeyra’s services, unless a different written fee is expressly agreed for that transaction.', 'The agreement must identify who pays the 1% fee and the completion event that makes it due. Unless otherwise stated, the fee is separate from the property purchase price.'] },
      { title: '4. When the fee becomes due', body: ['Unless the transaction-specific agreement states a different lawful trigger, the 1% fee becomes due when the transaction reaches the agreed completion event, such as completion of the sale, official transfer or registration, or execution of the legally effective sale agreement, as applicable to the transaction and jurisdiction.'] },
      { title: '5. No custody of transaction funds', body: ['AssetVeyra does not receive, hold, safeguard, control or transfer the purchase price, deposit or other property transaction funds. The buyer and seller arrange payment directly through the applicable legal, banking, registration or conveyancing process. AssetVeyra is not an escrow agent, bank or payment processor for the property purchase price.'] },
      { title: '6. Anti-circumvention and introduced parties', body: ['Where AssetVeyra introduces or materially facilitates contact between parties concerning an opportunity, the parties agree not to deliberately bypass AssetVeyra in order to avoid the agreed fee. If the parties complete the same or substantially related transaction with an introduced counterparty during the protection period stated in the transaction-specific agreement, the agreed 1% fee remains payable, subject to applicable law.', 'AssetVeyra should retain records of introductions, communications, offers, negotiations and transaction milestones sufficient to establish the service provided and the agreed fee.'] },
      { title: '7. Seller and buyer confirmations', body: ['Each party confirms that it has authority to enter the transaction and will provide accurate material information and documents. Each party is responsible for its own representations, approvals and obligations.'], bullets: ['The seller confirms authority to sell or otherwise offer the asset.', 'The buyer confirms authority and lawful capacity to purchase.', 'Neither party will knowingly provide materially false or misleading information.', 'Each party will disclose material restrictions, claims, encumbrances or circumstances relevant to the transaction where legally required.'] },
      { title: '8. Legal and professional providers', body: ['AssetVeyra may coordinate law firms and other professional specialists under separate arrangements. Legal advice, document drafting, title review, valuation, inspection and other regulated professional services remain the responsibility of the appointed professional within the scope of its engagement. Third-party professional fees are separate from AssetVeyra’s 1% fee unless expressly agreed otherwise.'] },
      { title: '9. Third-party costs and travel', body: ['Government charges, registration fees, legal fees, valuation and inspection fees, flights, accommodation, transport and other third-party costs are not included in the 1% fee unless expressly stated in writing. AssetVeyra may coordinate these services but does not guarantee third-party performance.'] },
      { title: '10. No guarantee of closing', body: ['AssetVeyra facilitates the transaction but does not guarantee that the parties will agree, that financing will be available, that title will be transferable, or that the transaction will close. Legal completion depends on the applicable law, documents, approvals and actions of the relevant parties and authorities.'] },
      { title: '11. Client protection and cooperation', body: ['The client must promptly disclose information that could affect the transaction and cooperate with reasonable verification, compliance and documentation requests. AssetVeyra may pause or terminate services where information is materially false, the transaction is unlawful, required approvals are unavailable, sanctions or compliance concerns arise, or continuing would expose AssetVeyra or its partners to material legal risk.'] },
      { title: '12. Evidence, records and electronic acceptance', body: ['The parties may use electronic acceptance, messages, signed documents and transaction records to evidence the agreed services, fee and milestones, subject to applicable electronic-transactions law. The transaction-specific agreement should identify the client, property/opportunity, fee payer, 1% fee, completion trigger, protection period and governing law.'] },
      { title: '13. Governing law', body: ['The governing law and dispute forum should be stated in the transaction-specific agreement. For Jordan transactions, the agreement must be aligned with applicable Jordanian real-estate, licensing, registration, professional and consumer laws. Cross-border transactions require jurisdiction-specific review.'] },
    ],
    notice: 'Legal protection depends on the actual licensed structure, the transaction-specific agreement and the law governing the transaction. This template should be reviewed by qualified counsel before being used as a binding contract.'
  },
  ar: {
    eyebrow: 'اتفاقية المعاملة', title: 'اتفاقية خدمات المعاملة وأتعاب 1%', updated: 'تاريخ السريان: 16 سبتمبر 2026',
    intro: 'تحدد هذه الصيغة العلاقة التجارية بين AssetVeyra والعميل الذي يستخدم خدماتها للبحث عن المعاملة العقارية والتفاوض بشأنها وتنسيقها. ويجوز أن تكملها اتفاقية خاصة بكل معاملة أو تحل محلها عندما يتطلب القانون ذلك.',
    sections: [
      { title: '1. نطاق خدمات AssetVeyra', body: ['يجوز لـAssetVeyra استقبال طلب العميل وتجهيزه، والبحث عن الفرص ومطابقتها، والتواصل مع المالكين والمشترين، ونقل العروض والعروض المقابلة، وتسهيل التفاوض التجاري، وتنسيق مراحل المعاملة، وتنسيق الوصول إلى المحامين والمختصين، وترتيب الجوانب العملية للسفر عند حاجة المعاملة لذلك.'] },
      { title: '2. السعر النهائي والقرار', body: ['يجوز لـAssetVeyra التفاوض وتسهيل الوصول إلى نتيجة تجارية مقبولة للطرفين، لكن المشتري والبائع هما صاحبا القرار في اعتماد السعر النهائي والشروط التعاقدية. ولا تملك AssetVeyra إلزام أي طرف بالبيع أو الشراء إلا بموجب تفويض خطي مستقل وصريح.'] },
      { title: '3. أتعاب AssetVeyra — 1%', body: ['تبلغ أتعاب خدمة المعاملة القياسية لـAssetVeyra نسبة 1% من قيمة المعاملة النهائية المتفق عليها عند إتمام المعاملة من خلال خدمات AssetVeyra، ما لم يتم الاتفاق خطياً على أتعاب مختلفة للمعاملة المحددة.', 'يجب أن تحدد اتفاقية المعاملة الطرف المسؤول عن دفع نسبة 1% والحدث الذي يجعلها مستحقة. وما لم يتفق على خلاف ذلك، تكون الأتعاب منفصلة عن ثمن العقار.'] },
      { title: '4. استحقاق الأتعاب', body: ['ما لم تنص اتفاقية المعاملة على نقطة استحقاق قانونية مختلفة، تستحق نسبة 1% عند تحقق نقطة الإتمام المتفق عليها، مثل إتمام البيع أو نقل/تسجيل الملكية رسمياً أو توقيع عقد البيع النافذ قانوناً، بحسب طبيعة المعاملة والقانون المطبق.'] },
      { title: '5. عدم حيازة أموال المعاملة', body: ['لا تستلم AssetVeyra أو تحتفظ أو تتحكم أو تحول ثمن العقار أو العربون أو أي أموال خاصة بمعاملة العقار. ويتولى المشتري والبائع الدفع مباشرة بينهما وفق الإجراءات القانونية أو المصرفية أو إجراءات التسجيل ونقل الملكية المعمول بها. ولا تعمل AssetVeyra كحساب ضمان أو بنك أو معالج دفع لثمن العقار.'] },
      { title: '6. منع الالتفاف وحماية الأطراف التي تم التعريف بها', body: ['عندما تقوم AssetVeyra بالتعريف بين الأطراف أو تسهيل التواصل بشأن فرصة معينة، يتعهد الأطراف بعدم الالتفاف عليها عمداً بقصد تجنب الأتعاب المتفق عليها. وإذا أتم الأطراف المعاملة نفسها أو معاملة مرتبطة بها بصورة جوهرية مع الطرف الذي عرّفتهم به AssetVeyra خلال مدة الحماية المحددة في الاتفاقية الخاصة بالمعاملة، تبقى نسبة 1% مستحقة، بالقدر الذي يسمح به القانون.', 'يجب أن تحتفظ AssetVeyra بسجلات للتعريف والتواصل والعروض والمفاوضات ومراحل المعاملة بما يكفي لإثبات الخدمة والأتعاب المتفق عليها.'] },
      { title: '7. إقرارات البائع والمشتري', body: ['يقر كل طرف بأن لديه الصلاحية للدخول في المعاملة وأن المعلومات والمستندات التي يقدمها دقيقة في الجوانب الجوهرية، ويتحمل كل طرف مسؤولية إقراراته وموافقاته والتزاماته.'], bullets: ['يؤكد البائع أن لديه الصلاحية القانونية لبيع العقار أو عرضه.', 'يؤكد المشتري أهليته وصلاحيته القانونية للشراء.', 'لا يقدم أي طرف عن علم معلومات جوهرية كاذبة أو مضللة.', 'يفصح كل طرف عن القيود أو المطالبات أو الحقوق أو الرهون أو الظروف الجوهرية ذات الصلة عندما يوجب القانون ذلك.'] },
      { title: '8. المحامون والمختصون المهنيون', body: ['يجوز لـAssetVeyra تنسيق خدمات مكاتب المحاماة والمختصين الآخرين بموجب ترتيبات منفصلة. وتبقى الاستشارة القانونية وإعداد المستندات وفحص الملكية والتقييم والفحص والخدمات المهنية المنظمة مسؤولية المختص المعين ضمن نطاق تكليفه. وتكون أتعاب الأطراف الثالثة منفصلة عن نسبة 1% ما لم يتفق خطياً على خلاف ذلك.'] },
      { title: '9. تكاليف الأطراف الثالثة والسفر', body: ['الرسوم الحكومية ورسوم التسجيل وأتعاب المحامين والتقييم والفحص وتذاكر السفر والإقامة والنقل وغيرها من تكاليف الأطراف الثالثة لا تدخل ضمن نسبة 1% ما لم ينص على ذلك خطياً. ويجوز لـAssetVeyra تنسيق هذه الخدمات دون ضمان أداء الطرف الثالث.'] },
      { title: '10. عدم ضمان إتمام الصفقة', body: ['تقوم AssetVeyra بتسهيل المعاملة لكنها لا تضمن اتفاق الأطراف أو توفر التمويل أو قابلية نقل الملكية أو إتمام الصفقة. ويعتمد الإتمام القانوني على القانون والمستندات والموافقات وإجراءات الأطراف والجهات المختصة.'] },
      { title: '11. حماية العميل والتعاون', body: ['يلتزم العميل بالإفصاح في الوقت المناسب عن المعلومات التي قد تؤثر في المعاملة والتعاون مع طلبات التحقق والامتثال والمستندات المعقولة. ويجوز لـAssetVeyra إيقاف أو إنهاء الخدمة إذا كانت المعلومات جوهرية الكذب أو التضليل، أو كانت المعاملة غير قانونية، أو تعذر الحصول على الموافقات اللازمة، أو ظهرت مخاطر عقوبات أو امتثال، أو أصبح استمرار الخدمة يعرض AssetVeyra أو شركاءها لمخاطر قانونية جوهرية.'] },
      { title: '12. الإثبات والسجلات والقبول الإلكتروني', body: ['يجوز استخدام القبول الإلكتروني والرسائل والمستندات الموقعة وسجلات المعاملة لإثبات الخدمات والأتعاب والمراحل المتفق عليها، وفق القانون المطبق. ويجب أن تحدد الاتفاقية الخاصة بالمعاملة العميل والعقار أو الفرصة والطرف الذي يدفع الأتعاب ونسبة 1% ونقطة الاستحقاق ومدة الحماية والقانون المطبق.'] },
      { title: '13. القانون الواجب التطبيق', body: ['يجب تحديد القانون والجهة المختصة في اتفاقية المعاملة الخاصة. وفي المعاملات الأردنية يجب مواءمة الاتفاقية مع القوانين الأردنية المتعلقة بالعقار والترخيص والتسجيل والخدمات المهنية وحقوق المستهلك. أما المعاملات الدولية فتتطلب مراجعة قانونية خاصة بكل دولة.'] },
    ],
    notice: 'تعتمد الحماية القانونية على الهيكل المرخص فعلياً وعلى اتفاقية المعاملة الخاصة والقانون الواجب التطبيق. يجب مراجعة هذه الصيغة من محامٍ مختص قبل استخدامها كعقد ملزم.'
  },
  zh: { eyebrow: '交易协议', title: '交易服务及1%费用协议', updated: '生效日期：2026年9月16日', intro: '本模板用于记录AssetVeyra与客户之间就房地产机会搜索、谈判和交易协调形成的商业关系。具体交易可根据适用法律另行签署交易协议。', sections: [{title:'1. 服务范围',body:['AssetVeyra可接收并整理客户需求、寻找和匹配机会、联系买卖双方、传递报价和反报价、协助商业谈判、协调交易流程，并协调律师及其他专业服务。']},{title:'2. 最终价格',body:['AssetVeyra可协助谈判，但最终价格和合同条件由买卖双方自行批准。']},{title:'3. 1%费用',body:['成功完成的交易标准服务费为最终约定交易价值的1%，除非具体交易书面约定其他费用。应书面确定付款方和费用触发条件。']},{title:'4. 不持有交易资金',body:['AssetVeyra不接收、保管或控制房地产购买价款、定金或其他交易资金。价款由买卖双方通过适用的法律、银行、登记或过户程序直接支付。']},{title:'5. 反规避',body:['双方不得故意绕过AssetVeyra以逃避已约定的费用。对于AssetVeyra介绍的交易对手，在具体协议约定的保护期内完成同一或实质相关交易的，适用法律允许的范围内仍应支付约定费用。']},{title:'6. 专业服务',body:['律师、评估师、检查人员等提供独立专业服务，其费用与AssetVeyra的1%费用分开。']},{title:'7. 法律审查',body:['本模板应由适用司法辖区的合格律师审查后用于具有约束力的交易。']}], notice:'本模板不是针对所有国家的最终法律意见；实际保护取决于许可结构、具体交易协议和适用法律。'},
  es: { eyebrow: 'ACUERDO DE TRANSACCIÓN', title: 'Acuerdo de servicios de transacción y tarifa del 1%', updated: 'Fecha de vigencia: 16 de septiembre de 2026', intro: 'Este modelo establece la relación comercial entre AssetVeyra y el cliente para buscar, negociar y coordinar una operación inmobiliaria.', sections: [{title:'1. Servicios',body:['AssetVeyra puede recibir y preparar solicitudes, buscar y emparejar oportunidades, contactar a las partes, transmitir ofertas, facilitar negociaciones y coordinar servicios profesionales.']},{title:'2. Precio final',body:['AssetVeyra puede facilitar la negociación, pero comprador y vendedor aprueban el precio y las condiciones finales.']},{title:'3. Tarifa del 1%',body:['La tarifa estándar es el 1% del valor final acordado de una operación completada mediante los servicios de AssetVeyra, salvo acuerdo escrito distinto.']},{title:'4. Fondos',body:['AssetVeyra no recibe ni custodia el precio de compra, depósitos u otros fondos de la operación. El pago se realiza directamente entre comprador y vendedor mediante el proceso legal aplicable.']},{title:'5. No elusión',body:['Las partes no deberán eludir deliberadamente a AssetVeyra para evitar la tarifa acordada.']},{title:'6. Profesionales',body:['Los abogados y otros profesionales prestan servicios independientes y sus honorarios son separados de la tarifa del 1%.']},{title:'7. Revisión legal',body:['Este modelo debe ser revisado por asesoría jurídica cualificada antes de utilizarse como contrato vinculante.']}], notice:'La protección jurídica depende de la estructura autorizada, del acuerdo específico y de la ley aplicable.'},
  fr: { eyebrow: 'ACCORD DE TRANSACTION', title: 'Accord de services de transaction et frais de 1 %', updated: 'Date d’effet : 16 septembre 2026', intro: 'Ce modèle encadre la relation commerciale entre AssetVeyra et le client pour rechercher, négocier et coordonner une opération immobilière.', sections: [{title:'1. Services',body:['AssetVeyra peut recevoir et préparer les demandes, rechercher et faire correspondre des opportunités, contacter les parties, transmettre les offres, faciliter les négociations et coordonner les services professionnels.']},{title:'2. Prix final',body:['AssetVeyra peut faciliter la négociation, mais l’acheteur et le vendeur approuvent le prix et les conditions finales.']},{title:'3. Frais de 1 %',body:['Les frais standards sont de 1 % de la valeur finale convenue d’une transaction réalisée grâce aux services d’AssetVeyra, sauf accord écrit différent.']},{title:'4. Fonds',body:['AssetVeyra ne reçoit ni ne conserve le prix d’achat, les dépôts ou autres fonds de la transaction. Le paiement est effectué directement entre acheteur et vendeur selon le processus légal applicable.']},{title:'5. Non-contournement',body:['Les parties ne doivent pas contourner délibérément AssetVeyra afin d’éviter les frais convenus.']},{title:'6. Professionnels',body:['Les avocats et autres professionnels fournissent des services indépendants et leurs honoraires sont distincts des frais de 1 %.']},{title:'7. Revue juridique',body:['Ce modèle doit être examiné par un conseil juridique qualifié avant toute utilisation comme contrat contraignant.']}], notice:'La protection juridique dépend de la structure autorisée, de l’accord spécifique et du droit applicable.'}
};

export default function TransactionAgreementPage() {
  const locale = useLocale();
  const copy = COPY[locale] ?? COPY.en;
  return <main className="app-shell"><section className="form-page legal-page"><div className="eyebrow">{copy.eyebrow}</div><h1>{copy.title}</h1><p className="muted">{copy.updated}</p><p>{copy.intro}</p>{copy.sections.map((s)=><section key={s.title}><h2>{s.title}</h2>{s.body.map((p)=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map((b)=><li key={b}>{b}</li>)}</ul>}</section>)}<div className="notice">{copy.notice}</div></section></main>;
}
