import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

const ADMIN_ROLES = ['platform_admin','operations_admin','compliance_officer'];

export default async function WorkspacePage() {
  const s = await createClient();
  const { data: { user } } = await s.auth.getUser();
  if (!user) redirect('/login');
  const { data: memberships } = await s.from('organization_members').select('organization_id,role,organizations(display_name,type)').eq('user_id', user.id);
  const orgIds = (memberships ?? []).map((m:any) => m.organization_id);
  const isAdmin = (memberships ?? []).some((m:any) => ADMIN_ROLES.includes(m.role));
  const [{ data: assets }, { data: interests }, { data: deals }, { data: rooms }] = await Promise.all([
    orgIds.length ? s.from('assets').select('id,title,status,asset_type,city,country_code,area_sqm,asking_price,currency,updated_at').in('organization_id', orgIds).order('updated_at',{ascending:false}).limit(8) : Promise.resolve({data:[]} as any),
    orgIds.length ? s.from('investor_interests').select('id,status,created_at,opportunities(slug,assets(title))').in('investor_organization_id', orgIds).order('created_at',{ascending:false}).limit(8) : Promise.resolve({data:[]} as any),
    orgIds.length ? s.from('deals').select('id,status,target_close_date,opportunities(slug,assets(title))').or(`organization_id.in.(${orgIds.join(',')}),buyer_organization_id.in.(${orgIds.join(',')}),seller_organization_id.in.(${orgIds.join(',')})`).order('updated_at',{ascending:false}).limit(8) : Promise.resolve({data:[]} as any),
    orgIds.length ? s.from('data_rooms').select('id,name,status,nda_required,download_enabled,opportunities(slug,assets(title))').in('organization_id', orgIds).order('updated_at',{ascending:false}).limit(8) : Promise.resolve({data:[]} as any)
  ]);
  return <main className="app-shell"><header className="app-header"><a className="brand" href="/">ASSETVEYRA</a><nav><a href="/opportunities">Marketplace</a><a href="/workspace">Workspace</a><form action="/logout" method="post"><button className="text-button">Sign out</button></form></nav></header><section className="page-head"><div className="eyebrow">INSTITUTIONAL WORKSPACE</div><h1>Transaction control.</h1><p>One workspace for asset intake, investor pipeline, data rooms and live deals. Every sensitive record remains organization-scoped.</p></section>{isAdmin && <section className="panel"><div className="panel-title"><div><div className="eyebrow">CONTROL</div><h2>Operations</h2></div></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><a className="button primary" href="/workspace/admin">Open platform controls</a><a className="button" href="/workspace/review">Open verification queue</a></div></section>}<section className="panel"><div className="panel-title"><div><div className="eyebrow">OPERATIONS</div><h2>Modules</h2></div></div><div className="opportunity-grid" style={{padding:'0'}}><a className="opportunity-card" href="/workspace/assets"><div className="card-meta"><span>SELLER</span><span>{assets?.length ?? 0}</span></div><h2>Assets & verification</h2><p>Track submitted assets, verification state and publication readiness.</p><strong>Open workspace →</strong></a><a className="opportunity-card" href="/workspace/interests"><div className="card-meta"><span>INVESTOR</span><span>{interests?.length ?? 0}</span></div><h2>Investor pipeline</h2><p>Monitor interests from qualification through NDA, diligence, offer and negotiation.</p><strong>Open pipeline →</strong></a><a className="opportunity-card" href="/workspace/data-rooms"><div className="card-meta"><span>DATA ROOM</span><span>{rooms?.length ?? 0}</span></div><h2>Private data rooms</h2><p>Control document access, NDA gates, expiry and download policy.</p><strong>Open data rooms →</strong></a><a className="opportunity-card" href="/workspace/deals"><div className="card-meta"><span>DEALS</span><span>{deals?.length ?? 0}</span></div><h2>Deal execution</h2><p>Follow the transaction lifecycle from initiation to closing.</p><strong>Open deals →</strong></a></div></section><section className="panel"><div className="panel-title"><div><div className="eyebrow">ORGANIZATIONS</div><h2>Your access</h2></div></div><div className="table">{(memberships ?? []).map((m:any)=><div className="row" key={`${m.organization_id}-${m.role}`}><strong>{m.organizations?.display_name}</strong><span>{m.organizations?.type}</span><span>{m.role}</span></div>)}</div></section></main>;
}
