import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export default async function DashboardPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login');
 const {data:members}=await supabase.from('organization_members').select('organization_id,role,organizations(display_name,type)').eq('user_id',user.id);
 const {data:opportunities}=await supabase.from('opportunities').select('id,slug,status,visibility,investment_thesis,minimum_ticket,target_return,assets(title,country_code,city,asset_type)').order('created_at',{ascending:false}).limit(12);
 return <main className="app-shell"><header className="app-header"><a className="brand" href="/">ASSETVEYRA</a><nav><a href="/opportunities">Marketplace</a><a href="/dashboard">Workspace</a><form action="/logout" method="post"><button className="text-button">Sign out</button></form></nav></header><section className="dashboard-head"><div><div className="eyebrow">CONTROL CENTER</div><h1>Transaction workspace</h1><p>Authenticated as {user.email}</p></div><a className="button primary" href="/submit">Submit asset</a></section><section className="stats"><div><span>Organizations</span><strong>{members?.length||0}</strong></div><div><span>Published opportunities</span><strong>{opportunities?.filter(o=>o.status==='published').length||0}</strong></div><div><span>Pipeline records</span><strong>{opportunities?.length||0}</strong></div></section><section className="panel"><div className="panel-title"><div><div className="eyebrow">YOUR ORGANIZATIONS</div><h2>Access and roles</h2></div></div><div className="table">{members?.map((m:any)=><div className="row" key={`${m.organization_id}-${m.role}`}><strong>{m.organizations?.display_name}</strong><span>{m.organizations?.type}</span><span>{m.role}</span></div>)}</div></section><section className="panel"><div className="panel-title"><div><div className="eyebrow">LIVE DATA</div><h2>Recent opportunities</h2></div><a href="/opportunities">View marketplace</a></div><div className="table">{opportunities?.map((o:any)=><a className="row" href={`/opportunities/${o.slug}`} key={o.id}><strong>{o.assets?.title||o.slug}</strong><span>{o.assets?.city||o.assets?.country_code||'—'}</span><span>{o.status}</span></a>)}</div></section></main>
}
