import { createClient } from '@/lib/supabase/server';
import { I18nText } from '@/components/LocaleShell';

type Opportunity = { id:string; slug:string; status:string; investment_thesis:string|null; structure:string|null; minimum_ticket:number|null; target_return:number|null; asset_id:string };
type Asset = { id:string; title:string; asset_type:string; country_code:string|null; region:string|null; city:string|null; area_sqm:number|null; currency:string|null; asking_price:number|null; public_summary:string|null };
const MIN_PUBLIC_VALUE = 100_000;
const sectorKeys:Record<string,string>={land:'Land',residential:'Residential',commercial:'Commercial',hotel:'Hotel',hospitality:'Hospitality',industrial:'Industrial',mixed_use:'Mixed use',development_project:'Development project',infrastructure:'Infrastructure',renewable_energy:'Renewable energy',other:'Other'};

export default async function OpportunitiesPage() {
  const s=await createClient();
  const {data:{user}}=await s.auth.getUser();
  const {data:opportunities,error:opportunityError}=await s.from('opportunities').select('id,slug,status,investment_thesis,structure,minimum_ticket,target_return,asset_id').eq('status','published').order('published_at',{ascending:false});
  let assets:Asset[]=[]; let assetError=null;
  if(!opportunityError&&opportunities?.length){const assetIds=(opportunities as Opportunity[]).map(item=>item.asset_id).filter(Boolean);if(assetIds.length){const result=await s.from('assets').select('id,title,asset_type,country_code,region,city,area_sqm,currency,asking_price,public_summary').in('id',assetIds);assets=(result.data??[]) as Asset[];assetError=result.error;}}
  const assetById=new Map(assets.map(asset=>[asset.id,asset]));
  const rows=(opportunities??[]).map(opportunity=>({opportunity:opportunity as Opportunity,asset:assetById.get((opportunity as Opportunity).asset_id)})).filter(({asset})=>Boolean(asset?.asking_price&&Number(asset.asking_price)>=MIN_PUBLIC_VALUE));
  const error=opportunityError||assetError;
  return <main className="app-shell"><header className="app-header"><a className="brand" href="/">ASSETVEYRA</a><nav><a href="/opportunities"><I18nText id="Opportunities"/></a><a href="/dashboard"><I18nText id="Workspace"/></a>{user?<form action="/logout" method="post"><button className="text-button"><I18nText id="Sign out"/></button></form>:<a href="/login"><I18nText id="Sign in"/></a>}</nav></header><section className="page-head"><div className="eyebrow"><I18nText id="Market"/></div><h1><I18nText id="Opportunities"/></h1><p><I18nText id="Curated opportunities for qualified investors worldwide."/></p></section>{error?<div className="form-error"><I18nText id="The live marketplace could not be loaded. Please try again shortly."/></div>:<section className="opportunity-grid">{rows.map(({opportunity,asset})=>asset?<a className="opportunity-card" href={user?`/opportunities/${opportunity.slug}`:'/login'} key={opportunity.id}>{user?<><div className="card-meta"><span>{sectorKeys[asset.asset_type]?<I18nText id={sectorKeys[asset.asset_type]}/>:asset.asset_type}</span><span>{asset.country_code??'—'}</span></div><h2>{asset.title}</h2><p>{asset.public_summary||opportunity.investment_thesis||<I18nText id="Investment opportunity"/>}</p><div className="card-data"><span>{asset.city||asset.region||'—'}</span><strong>{asset.currency||'USD'} {Number(asset.asking_price).toLocaleString()}</strong></div></>:<><div className="card-meta"><span><I18nText id="Investment opportunity"/></span><span>{asset.country_code??'—'}</span></div><h2>{asset.country_code??'Global'}</h2><p><I18nText id="Register"/></p><div className="card-data"><span><I18nText id="Asking price"/></span><strong>{asset.currency||'USD'} {Number(asset.asking_price).toLocaleString()}</strong></div></>}</a>:null)}{!rows.some(({asset})=>asset)&&<div className="empty-state wide"><strong><I18nText id="No published opportunities yet"/></strong><span><I18nText id="No sample or fabricated inventory is displayed."/></span></div>}</section>}</main>;
}
