'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function OnboardingPage(){
 const [type,setType]=useState('investor'); const [displayName,setDisplayName]=useState(''); const [legalName,setLegalName]=useState(''); const [country,setCountry]=useState('JO'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await createClient().rpc('create_organization',{p_type:type,p_legal_name:legalName||null,p_display_name:displayName,p_country_code:country});if(error)setError(error.message);else window.location.href='/dashboard';setBusy(false)}
 return <main className="auth-page"><section className="auth-card"><a className="brand" href="/">ASSETVEYRA</a><div className="eyebrow">ORGANIZATION SETUP</div><h1>Set up your workspace</h1><p>Your organization is the security boundary for assets, documents and transactions.</p><form onSubmit={submit}><label>Organization type<select value={type} onChange={e=>setType(e.target.value)}><option value="investor">Investor</option><option value="seller">Seller</option><option value="advisor">Advisor</option><option value="broker">Broker</option><option value="legal">Legal</option><option value="service_provider">Service provider</option></select></label><label>Display name<input required value={displayName} onChange={e=>setDisplayName(e.target.value)} /></label><label>Legal name<input value={legalName} onChange={e=>setLegalName(e.target.value)} /></label><label>Country code<input required maxLength={2} value={country} onChange={e=>setCountry(e.target.value.toUpperCase())} /></label>{error&&<div className="form-error">{error}</div>}<button className="button primary" disabled={busy}>{busy?'Creating…':'Create workspace'}</button></form></section></main>
}
