export const SUPPORTED_LOCALES = ['en', 'ar', 'zh', 'es', 'fr'] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export const LOCALE_LABELS: Record<Locale,string> = { en:'English', ar:'العربية', zh:'中文', es:'Español', fr:'Français' };
export const RTL_LOCALES = new Set<Locale>(['ar']);
export function normalizeLocale(value?: string|null): Locale { const base=(value??'').toLowerCase().split('-')[0]; return (SUPPORTED_LOCALES as readonly string[]).includes(base) ? base as Locale : 'en'; }
export function detectLocaleFromLanguages(languages: readonly string[]): Locale { for(const language of languages){ const base=(language??'').toLowerCase().split('-')[0]; if((SUPPORTED_LOCALES as readonly string[]).includes(base)) return base as Locale; } return 'en'; }
type TranslationSet = Record<Locale,string>;
const T = (en:string, ar:string, zh:string, es:string, fr:string): TranslationSet => ({en,ar,zh,es,fr});
export const TRANSLATIONS: Record<string,TranslationSet> = {
  'Menu':T('Menu','القائمة','菜单','Menú','Menu'),'Home':T('Home','الرئيسية','首页','Inicio','Accueil'),'Opportunities':T('Opportunities','الفرص','投资机会','Oportunidades','Opportunités'),'Details':T('Details','التفاصيل','详情','Detalles','Détails'),'Dashboard':T('Dashboard','لوحة التحكم','控制面板','Panel','Tableau de bord'),'About':T('About','من نحن','关于我们','Nosotros','À propos'),'Contact':T('Contact','اتصل بنا','联系我们','Contacto','Contact'),'Legal':T('Legal','قانوني','法律信息','Legal','Mentions légales'),'Language':T('Language','اللغة','语言','Idioma','Langue'),'Login':T('Login','تسجيل الدخول','登录','Iniciar sesión','Se connecter'),'Sign Up':T('Sign Up','إنشاء حساب','注册','Registrarse','Créer un compte'),'Sign in':T('Sign in','تسجيل الدخول','登录','Iniciar sesión','Se connecter'),'Sign out':T('Sign out','تسجيل الخروج','退出登录','Cerrar sesión','Se déconnecter'),
  'Exclusive Access to $100,000+ Assets':T('Exclusive Access to $100,000+ Assets','وصول حصري إلى أصول بقيمة 100,000 دولار فأكثر','独家访问价值10万美元以上的资产','Acceso exclusivo a activos de más de 100.000 $','Accès exclusif à des actifs de plus de 100 000 $'),'Curated opportunities for qualified investors worldwide.':T('Curated opportunities for qualified investors worldwide.','فرص منتقاة للمستثمرين المؤهلين حول العالم.','为全球合格投资者精选的机会。','Oportunidades seleccionadas para inversores cualificados de todo el mundo.','Opportunités sélectionnées pour des investisseurs qualifiés dans le monde entier.'),'View Opportunities':T('View Opportunities','استكشف الفرص','查看投资机会','Ver oportunidades','Voir les opportunités'),
  'Minimum Asset Value: $100,000+':T('Minimum Asset Value: $100,000+','الحد الأدنى لقيمة الأصل: 100,000 دولار فأكثر','最低资产价值：10万美元以上','Valor mínimo del activo: 100.000 $','Valeur minimale de l’actif : 100 000 $'),'Verified Opportunities':T('Verified Opportunities','فرص تم التحقق منها','已验证机会','Oportunidades verificadas','Opportunités vérifiées'),'Global Coverage: 50+ Countries':T('Global Coverage: 50+ Countries','انتشار عالمي','全球覆盖','Alcance global','Portée mondiale'),'NDA-Protected Access':T('NDA-Protected Access','وصول منضبط إلى المعلومات الحساسة','受控访问敏感信息','Acceso controlado a información sensible','Accès contrôlé aux informations sensibles'),
  'How AssetVeyra Works':T('How AssetVeyra Works','كيف تعمل AssetVeyra','AssetVeyra 如何运作','Cómo funciona AssetVeyra','Comment fonctionne AssetVeyra'),'Discover':T('Discover','اكتشاف','发现','Descubrir','Découvrir'),'Register':T('Register','التسجيل','注册','Registrarse','S’inscrire'),'Qualify':T('Qualify','التأهيل','资格审查','Cualificación','Qualifier'),'NDA':T('NDA','اتفاقية عدم الإفصاح','保密协议','Acuerdo de confidencialidad','Accord de confidentialité'),'Data Room':T('Data Room','غرفة البيانات','数据室','Sala de datos','Data room'),'Due Diligence':T('Due Diligence','العناية الواجبة','尽职调查','Due diligence','Due diligence'),'Offer':T('Offer','العرض','报价','Oferta','Offre'),'Deal / Closing':T('Deal / Closing','الصفقة / الإغلاق','交易 / 交割','Operación / Cierre','Transaction / Clôture'),
  'Access Model':T('Access Model','نموذج الوصول','访问模式','Modelo de acceso','Modèle d’accès'),'Public information':T('Public information','المعلومات العامة','公开信息','Información pública','Informations publiques'),'Registered access':T('Registered access','الوصول للمستخدمين المسجلين','注册用户访问','Acceso registrado','Accès enregistré'),'Qualified access':T('Qualified access','الوصول بعد التأهيل','资格审查后的访问','Acceso cualificado','Accès qualifié'),'NDA-gated information':T('NDA-gated information','معلومات تتطلب اتفاقية سرية','需要保密协议的信息','Información sujeta a NDA','Informations soumises à NDA'),'Security & Trust':T('Security & Trust','الأمان والثقة','安全与信任','Seguridad y confianza','Sécurité et confiance'),'Authentication':T('Authentication','المصادقة','身份验证','Autenticación','Authentification'),'Authorization':T('Authorization','التفويض','授权','Autorización','Autorisation'),'Organization isolation':T('Organization isolation','عزل بيانات المؤسسات','组织隔离','Aislamiento de organizaciones','Isolation des organisations'),'Role-based access':T('Role-based access','الوصول حسب الدور','基于角色的访问','Acceso basado en roles','Accès basé sur les rôles'),'Controlled Data Room access':T('Controlled Data Room access','وصول منضبط إلى غرفة البيانات','受控数据室访问','Acceso controlado a la sala de datos','Accès contrôlé à la data room'),'Auditability':T('Auditability','قابلية التدقيق','可审计性','Auditabilidad','Auditabilité'),
  'About AssetVeyra':T('About AssetVeyra','عن AssetVeyra','关于 AssetVeyra','Sobre AssetVeyra','À propos d’AssetVeyra'),'What is AssetVeyra?':T('What is AssetVeyra?','ما هي AssetVeyra؟','AssetVeyra 是什么？','¿Qué es AssetVeyra?','Qu’est-ce qu’AssetVeyra ?'),'Who is it for?':T('Who is it for?','لمن صُممت؟','面向谁？','¿Para quién es?','À qui s’adresse-t-elle ?'),'How does it work?':T('How does it work?','كيف تعمل؟','如何运作？','¿Cómo funciona?','Comment fonctionne-t-elle ?'),'Why the platform?':T('Why the platform?','لماذا المنصة؟','为什么选择平台？','¿Por qué la plataforma?','Pourquoi la plateforme ?'),'FAQ':T('FAQ','الأسئلة الشائعة','常见问题','Preguntas frecuentes','FAQ'),
  'Contact Us':T('Contact Us','اتصل بنا','联系我们','Contáctenos','Nous contacter'),'Tell us what you are looking for.':T('Tell us what you are looking for.','أخبرنا بما تبحث عنه.','告诉我们您正在寻找什么。','Cuéntenos qué está buscando.','Dites-nous ce que vous recherchez.'),'Send request':T('Send request','إرسال الطلب','发送请求','Enviar solicitud','Envoyer la demande'),'Sending…':T('Sending…','جارٍ الإرسال…','正在发送…','Enviando…','Envoi…'),'Your request has been received.':T('Your request has been received.','تم استلام طلبك.','我们已收到您的请求。','Hemos recibido su solicitud.','Votre demande a été reçue.'),'Unable to send the request.':T('Unable to send the request.','تعذر إرسال الطلب.','无法发送请求。','No se ha podido enviar la solicitud.','Impossible d’envoyer la demande.'),
  'Asset title':T('Asset title','اسم الأصل','资产名称','Título del activo','Nom de l’actif'),'Asset type':T('Asset type','نوع الأصل','资产类型','Tipo de activo','Type d’actif'),'Country code':T('Country code','رمز الدولة','国家代码','Código de país','Code pays'),'City':T('City','المدينة','城市','Ciudad','Ville'),'Area m²':T('Area m²','المساحة م²','面积（平方米）','Superficie m²','Surface m²'),'Currency':T('Currency','العملة','货币','Moneda','Devise'),'Asking price':T('Asking price','السعر المطلوب','要价','Precio solicitado','Prix demandé'),'Public summary':T('Public summary','الملخص العام','公开摘要','Resumen público','Résumé public'),'Submit Asset for Verification':T('Submit Asset for Verification','إرسال الأصل للتحقق','提交资产进行验证','Enviar activo para verificación','Soumettre l’actif pour vérification'),'The record enters verification first. It is not published automatically.':T('The record enters verification first. It is not published automatically.','يدخل السجل مرحلة التحقق أولًا ولا يتم نشره تلقائيًا.','记录首先进入验证阶段，不会自动发布。','El registro entra primero en verificación. No se publica automáticamente.','L’enregistrement passe d’abord par la vérification. Il n’est pas publié automatiquement.'),
  'Transaction Workspace':T('Transaction Workspace','مساحة تنفيذ المعاملة','交易工作区','Espacio de transacción','Espace de transaction'),'Investor Interests':T('Investor Interests','اهتمامات المستثمرين','投资者意向','Intereses de inversores','Intérêts des investisseurs'),'Transaction Pipeline':T('Transaction Pipeline','مسار المعاملات','交易流程','Pipeline de transacciones','Pipeline des transactions'),'Submit an asset':T('Submit an asset','إرسال أصل','提交资产','Enviar un activo','Soumettre un actif'),'Workspace':T('Workspace','مساحة العمل','工作区','Espacio de trabajo','Espace de travail'),'Marketplace':T('Marketplace','السوق','市场','Mercado','Marché'),'No published opportunities yet':T('No published opportunities yet','لا توجد فرص منشورة بعد','暂无已发布的机会','Aún no hay oportunidades publicadas','Aucune opportunité publiée pour le moment'),'No sample or fabricated inventory is displayed.':T('No sample or fabricated inventory is displayed.','لا يتم عرض مخزون تجريبي أو وهمي.','不会显示示例或虚构库存。','No se muestra inventario de muestra o ficticio.','Aucun inventaire fictif ou de démonstration n’est affiché.'),
  'Legal Information':T('Legal Information','المعلومات القانونية','法律信息','Información legal','Informations légales'),'Privacy':T('Privacy','الخصوصية','隐私','Privacidad','Confidentialité'),'Terms':T('Terms','الشروط','条款','Términos','Conditions'),'Security':T('Security','الأمان','安全','Seguridad','Sécurité'),'Legal & Compliance':T('Legal & Compliance','القانون والامتثال','法律与合规','Legal y cumplimiento','Juridique et conformité'),'LEGAL INPUT REQUIRED':T('LEGAL INPUT REQUIRED','مطلوب إدخال قانوني','需要法律信息','SE REQUIERE INFORMACIÓN LEGAL','INFORMATIONS JURIDIQUES REQUISES'),
  'Create account':T('Create account','إنشاء حساب','创建账户','Crear cuenta','Créer un compte'),'Terms/Privacy acknowledgement':T('Terms/Privacy acknowledgement','الإقرار بالشروط والخصوصية','确认条款与隐私','Aceptación de términos y privacidad','Acceptation des conditions et de la confidentialité'),'Processing…':T('Processing…','جارٍ المعالجة…','处理中…','Procesando…','Traitement…'),'Account created. Check your email to verify the account, then sign in.':T('Account created. Check your email to verify the account, then sign in.','تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد الحساب ثم سجّل الدخول.','账户已创建。请检查邮箱完成验证，然后登录。','Cuenta creada. Compruebe su correo para verificarla y después inicie sesión.','Compte créé. Vérifiez votre e-mail pour confirmer le compte, puis connectez-vous.'),
  'Institutional Workspace':T('Institutional Workspace','مساحة العمل المؤسسية','机构工作区','Espacio de trabajo institucional','Espace de travail institutionnel'),'Every sensitive record remains organization-scoped.':T('Every sensitive record remains organization-scoped.','تبقى كل السجلات الحساسة ضمن نطاق المؤسسة.','所有敏感记录均限定在所属组织范围内。','Cada registro sensible permanece dentro del ámbito de la organización.','Chaque enregistrement sensible reste limité à son organisation.'),'Assets & verification':T('Assets & verification','الأصول والتحقق','资产与验证','Activos y verificación','Actifs et vérification'),'Private data rooms':T('Private data rooms','غرف البيانات الخاصة','私人数据室','Salas de datos privadas','Data rooms privées'),'Deal execution':T('Deal execution','تنفيذ الصفقة','交易执行','Ejecución de operaciones','Exécution des transactions'),'Open workspace →':T('Open workspace →','فتح مساحة العمل ←','打开工作区 →','Abrir espacio de trabajo →','Ouvrir l’espace de travail →')
};
export function translate(key:string, locale:Locale):string { return TRANSLATIONS[key]?.[locale] ?? TRANSLATIONS[key]?.en ?? key; }
export const CORE_TRANSLATION_KEYS=Object.freeze(Object.keys(TRANSLATIONS));
