'use client';
import { createElement, type ElementType } from 'react';
import type { Locale } from './i18n';
import { translate, type Locale as AppLocale } from './i18n';
import { useLocale } from '@/components/LocaleShell';

export const HOME_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {}, de: {}, ja: {}, ko: {},
  ar: {'Market':'السوق','Platform':'المنصة','Workflow':'سير العمل','Sign in':'تسجيل الدخول','Submit an asset':'إضافة أصل','GLOBAL REAL-ASSET MARKET':'السوق العالمي للأصول الحقيقية','MARKET INTELLIGENCE':'ذكاء السوق','Source-checked opportunities':'فرص تم التحقق من مصادرها','GLOBAL REAL-ASSET TRANSACTION INFRASTRUCTURE':'بنية عالمية لمعاملات الأصول الحقيقية','Capital meets real assets.':'رأس المال يلتقي بالأصول الحقيقية.','Explore the market':'استكشف السوق','Real assets':'الأصول الحقيقية','Investor workspace':'مساحة عمل المستثمر','LIVE MARKET EXAMPLES':'أمثلة حية من السوق','External source':'مصدر خارجي','SOURCE CHECKED':'تم التحقق من المصدر','AREA':'المساحة','Request through AssetVeyra':'اطلب عبر AssetVeyra','THE PLATFORM':'المنصة','Built around the transaction, not the listing.':'مصممة حول المعاملة، وليس مجرد الإدراج.','Verified':'موثق','Structured opportunities':'فرص منظمة','Private':'خاص','Data rooms':'غرف بيانات','Execute':'تنفيذ','Transaction workflow':'سير عمل المعاملة','Control':'رقابة','Compliance architecture':'بنية الامتثال','TRANSACTION LIFECYCLE':'دورة حياة المعاملة','Intake':'الاستلام','Verification':'التحقق','Compliance':'الامتثال','Publication':'النشر','Qualification':'التأهيل','NDA':'اتفاقية عدم الإفصاح','Data Room':'غرفة البيانات','Diligence':'العناية الواجبة','Offer':'العرض','Negotiation':'التفاوض','Contract':'العقد','Closing':'الإغلاق','REAL-ASSET INTELLIGENCE':'ذكاء الأصول الحقيقية','Location intelligence':'ذكاء الموقع','Source evidence':'أدلة المصدر','Due diligence':'العناية الواجبة','Controlled disclosure':'الإفصاح الخاضع للرقابة','CONTROLLED INTRODUCTION':'تقديم خاضع للرقابة','Interested in an opportunity?':'مهتم بفرصة؟','Request property information':'اطلب معلومات العقار','Start a request':'ابدأ طلبًا','Security':'الأمان','Privacy':'الخصوصية','Terms':'الشروط','Contact AssetVeyra':'تواصل مع AssetVeyra','High-value commercial opportunities':'فرص تجارية عالية القيمة','Request information':'طلب معلومات'},
  es:{'Market':'Mercado','Platform':'Plataforma','Workflow':'Flujo de trabajo','Sign in':'Iniciar sesión','Submit an asset':'Enviar un activo','Capital meets real assets.':'El capital se encuentra con los activos reales.','Explore the market':'Explorar el mercado','Investor workspace':'Espacio de trabajo del inversor','Real assets':'Activos reales','THE PLATFORM':'LA PLATAFORMA','TRANSACTION LIFECYCLE':'CICLO DE VIDA DE LA TRANSACCIÓN','Verification':'Verificación','Compliance':'Cumplimiento','Publication':'Publicación','Qualification':'Calificación','NDA':'Acuerdo de confidencialidad','Data Room':'Sala de datos','Diligence':'Due diligence','Offer':'Oferta','Negotiation':'Negociación','Contract':'Contrato','Closing':'Cierre','Security':'Seguridad','Privacy':'Privacidad','Terms':'Términos'},
  fr:{'Market':'Marché','Platform':'Plateforme','Workflow':'Flux de travail','Sign in':'Se connecter','Submit an asset':'Soumettre un actif','Capital meets real assets.':'Le capital rencontre les actifs réels.','Explore the market':'Explorer le marché','Investor workspace':'Espace de travail de l’investisseur','Real assets':'Actifs réels','THE PLATFORM':'LA PLATEFORME','TRANSACTION LIFECYCLE':'CYCLE DE VIE DE LA TRANSACTION','Verification':'Vérification','Compliance':'Conformité','Publication':'Publication','Qualification':'Qualification','NDA':'Accord de confidentialité','Data Room':'Data room','Diligence':'Due diligence','Offer':'Offre','Negotiation':'Négociation','Contract':'Contrat','Closing':'Clôture','Security':'Sécurité','Privacy':'Confidentialité','Terms':'Conditions'},
  zh:{'Market':'市场','Platform':'平台','Workflow':'工作流程','Sign in':'登录','Submit an asset':'提交资产','Capital meets real assets.':'资本连接真实资产。','Explore the market':'探索市场','Investor workspace':'投资者工作区','Real assets':'真实资产','THE PLATFORM':'平台','TRANSACTION LIFECYCLE':'交易生命周期','Verification':'验证','Compliance':'合规','Publication':'发布','Qualification':'资格审查','NDA':'保密协议','Data Room':'数据室','Diligence':'尽职调查','Offer':'报价','Negotiation':'谈判','Contract':'合同','Closing':'交割','Security':'安全','Privacy':'隐私','Terms':'条款'}
};

export function translateHome(text: string, locale: Locale): string {
  const translated = translate(text, locale);
  return translated !== text ? translated : HOME_TRANSLATIONS[locale]?.[text] ?? text;
}

export function I18nText({ id, as = 'span' }: { id: string; as?: ElementType }) {
  const locale: AppLocale = useLocale();
  const value = translate(id, locale);
  return createElement(as, { 'data-i18n-component': 'true' }, value);
}
