import type { Locale } from './i18n';

/** Homepage strings kept in one place for the DOM fallback translator. */
export const HOME_TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {},
  ar: {
    'Market':'السوق','Platform':'المنصة','Workflow':'سير العمل','Sign in':'تسجيل الدخول','Submit an asset':'إضافة أصل',
    'GLOBAL REAL-ASSET MARKET':'السوق العالمي للأصول الحقيقية','MARKET INTELLIGENCE':'ذكاء السوق','Source-checked opportunities':'فرص تم التحقق من مصادرها','Prices shown in USD · external listings':'الأسعار معروضة بالدولار الأمريكي · قوائم خارجية',
    'GLOBAL REAL-ASSET TRANSACTION INFRASTRUCTURE':'بنية عالمية لمعاملات الأصول الحقيقية','Capital meets real assets.':'رأس المال يلتقي بالأصول الحقيقية.',
    'Discover real opportunities, understand the asset, control disclosure and move from qualified interest to executable transaction in one institutional workspace.':'اكتشف الفرص الحقيقية، وافهم الأصل، واضبط الإفصاح، وانتقل من الاهتمام المؤهل إلى معاملة قابلة للتنفيذ ضمن مساحة عمل مؤسسية واحدة.',
    'Discover high-value commercial opportunities, understand the asset, control disclosure and move from qualified interest to executable transaction in one institutional workspace.':'اكتشف الفرص التجارية عالية القيمة، وافهم الأصل، واضبط الإفصاح، وانتقل من الاهتمام المؤهل إلى معاملة قابلة للتنفيذ ضمن مساحة عمل مؤسسية واحدة.',
    'Explore the market':'استكشف السوق','Public market discovery is separated from private diligence, compliance and deal records.':'يُفصل اكتشاف السوق العام عن العناية الواجبة الخاصة والامتثال وسجلات الصفقات.',
    'Real assets':'الأصول الحقيقية','Source → Diligence → Deal':'المصدر ← العناية الواجبة ← الصفقة','Public → Controlled → Private':'عام ← خاضع للرقابة ← خاص','Investor workspace':'مساحة عمل المستثمر','GLOBAL':'عالمي','WORKFLOW':'سير العمل','DISCLOSURE':'الإفصاح','ACCESS':'الوصول',
    'LIVE MARKET EXAMPLES':'أمثلة حية من السوق','Real listings. Real asking prices. One controlled entry point.':'قوائم حقيقية. أسعار طلب حقيقية. نقطة دخول واحدة خاضعة للرقابة.',
    'These are external market listings sourced from public marketplaces, not AssetVeyra-owned inventory. Prices are converted to USD for comparison and must be reconfirmed before any transaction.':'هذه قوائم سوق خارجية مأخوذة من أسواق عامة وليست مخزونًا مملوكًا لـ AssetVeyra. تم تحويل الأسعار إلى الدولار للمقارنة ويجب إعادة التحقق منها قبل أي معاملة.',
    '10 opportunities':'10 فرص','USD display':'عرض بالدولار الأمريكي','Checked 14 Sep 2026':'تم التحقق في 14 سبتمبر 2026','External source':'مصدر خارجي','SOURCE CHECKED':'تم التحقق من المصدر','AREA':'المساحة','Request through AssetVeyra':'اطلب عبر AssetVeyra','Source listing ↗':'القائمة المصدر ↗',
    'Market listings are presented for discovery and comparison. AssetVeyra does not represent external listings as its own inventory unless a separate AssetVeyra verification and publication record is shown.':'تُعرض قوائم السوق للاكتشاف والمقارنة. لا تعتبر AssetVeyra القوائم الخارجية مخزونًا تابعًا لها إلا عند وجود سجل منفصل للتحقق والنشر من AssetVeyra.',
    'THE PLATFORM':'المنصة','Built around the transaction, not the listing.':'مصممة حول المعاملة، وليس مجرد الإدراج.','Verified':'موثق','Structured opportunities':'فرص منظمة','Private':'خاص','Data rooms':'غرف بيانات','Execute':'تنفيذ','Transaction workflow':'سير عمل المعاملة','Control':'رقابة','Compliance architecture':'بنية الامتثال',
    'Asset records, verification states and publication gates keep market discovery separate from controlled transaction data.':'تحافظ سجلات الأصول وحالات التحقق وبوابات النشر على فصل اكتشاف السوق عن بيانات المعاملات الخاضعة للرقابة.',
    'NDA gates, permissioned documents, versions, diligence requirements and activity history in one controlled workspace.':'بوابات اتفاقيات عدم الإفصاح والمستندات المصرح بها والإصدارات ومتطلبات العناية الواجبة وسجل النشاط في مساحة عمل واحدة خاضعة للرقابة.',
    'Interest, qualification, offers, negotiation, contracts, approvals and closing connected to the same transaction graph.':'الاهتمام والتأهيل والعروض والتفاوض والعقود والموافقات والإغلاق مترابطة ضمن منظومة المعاملة نفسها.',
    'KYC/KYB, AML, risk review and evidence stay isolated from public listing data and follow least-privilege access.':'تبقى إجراءات اعرف عميلك واعرف نشاطك ومكافحة غسل الأموال ومراجعة المخاطر والأدلة معزولة عن بيانات القوائم العامة وتخضع لمبدأ أقل صلاحية.',
    'TRANSACTION LIFECYCLE':'دورة حياة المعاملة','One controlled path from asset intake to closing.':'مسار واحد خاضع للرقابة من استلام الأصل حتى الإغلاق.','Intake':'الاستلام','Verification':'التحقق','Compliance':'الامتثال','Publication':'النشر','Qualification':'التأهيل','NDA':'اتفاقية عدم الإفصاح','Data Room':'غرفة البيانات','Diligence':'العناية الواجبة','Offer':'العرض','Negotiation':'التفاوض','Contract':'العقد','Closing':'الإغلاق',
    'REAL-ASSET INTELLIGENCE':'ذكاء الأصول الحقيقية','See the asset before you see the deal.':'اعرف الأصل قبل أن ترى الصفقة.','Location, physical characteristics, source evidence, verification state, diligence completeness and transaction history belong in the same decision environment.':'الموقع والخصائص المادية وأدلة المصدر وحالة التحقق واكتمال العناية الواجبة وتاريخ المعاملة يجب أن تكون ضمن بيئة قرار واحدة.','01 · Location intelligence':'01 · ذكاء الموقع','02 · Source evidence':'02 · أدلة المصدر','03 · Due diligence':'03 · العناية الواجبة','04 · Controlled disclosure':'04 · الإفصاح الخاضع للرقابة','ASSETVEYRA INTELLIGENCE':'ذكاء ASSETVEYRA','Location · Risk · Evidence':'الموقع · المخاطر · الأدلة',
    'CONTROLLED INTRODUCTION':'تقديم خاضع للرقابة','Interested in an opportunity?':'مهتم بفرصة؟','Start with AssetVeyra. We capture the opportunity request first, then route the appropriate information and transaction workflow through the platform.':'ابدأ مع AssetVeyra. نسجل طلب الفرصة أولًا، ثم نوجّه المعلومات المناسبة وسير عمل المعاملة عبر المنصة.','Request property information':'اطلب معلومات العقار','Start a request':'ابدأ طلبًا','No seller contact details are exposed on this public interface.':'لا يتم عرض بيانات اتصال البائع في هذه الواجهة العامة.','Global real-asset transaction infrastructure':'بنية عالمية لمعاملات الأصول الحقيقية','Security':'الأمان','Privacy':'الخصوصية','Terms':'الشروط',
    'GLOBAL HIGH-VALUE MARKET':'السوق العالمي للأصول عالية القيمة','High-value commercial opportunities':'فرص تجارية عالية القيمة','Prices shown in USD · market intelligence':'الأسعار معروضة بالدولار الأمريكي · معلومات سوقية','High-value assets':'أصول عالية القيمة','Commercial opportunities at institutional ticket sizes.':'فرص تجارية بقيم استثمارية كبيرة.','AssetVeyra focuses this public discovery layer on high-value commercial and development opportunities. Individual opportunities shown here are market intelligence examples and are not represented as AssetVeyra-owned inventory.':'تركز AssetVeyra في واجهة الاكتشاف العامة هذه على الفرص التجارية وفرص التطوير عالية القيمة. والفرص المعروضة هنا أمثلة لمعلومات السوق وليست أصولًا مملوكة لـ AssetVeyra.','4 opportunities':'4 فرص','Global commercial':'تجاري عالمي','Mixed-use beachfront development land':'أرض تطوير متعددة الاستخدامات على الواجهة البحرية','Prime beachfront development plot':'قطعة تطوير مميزة على الواجهة البحرية','Waterfront development land':'أرض تطوير على الواجهة المائية','Hospitality development land':'أرض تطوير لمشروع ضيافة','Request information':'طلب معلومات','Market examples are presented for discovery and comparison only. AssetVeyra does not expose third-party seller, broker or listing-platform contact details on this public interface. Any transaction requires separate AssetVeyra verification, qualification and controlled disclosure.':'تُعرض أمثلة السوق للاكتشاف والمقارنة فقط. لا تعرض AssetVeyra بيانات اتصال البائع أو الوسيط أو منصة الإدراج التابعة لطرف ثالث على هذه الواجهة العامة. وتتطلب أي معاملة تحققًا وتأهيلًا وإفصاحًا منضبطًا بشكل منفصل عبر AssetVeyra.',
    'Prime beachfront hotel development land':'أرض مميزة لتطوير فندق على الواجهة البحرية','Indicative market figure; final commercial terms require direct verification.':'قيمة سوقية إرشادية؛ تتطلب الشروط التجارية النهائية تحققًا مباشرًا.','UAE':'الإمارات','Egypt':'مصر','Ras Al Khaimah':'رأس الخيمة','Dubai':'دبي','Soma Bay':'سوما باي','Tell us what you are looking for.':'أخبرنا بما تبحث عنه.','We review the request first, then route the appropriate information and transaction workflow through AssetVeyra.':'نراجع الطلب أولًا، ثم نوجّه المعلومات المناسبة وسير عمل المعاملة عبر AssetVeyra.','Seller and broker contact details are not exposed on this public interface.':'لا يتم عرض بيانات اتصال البائع أو الوسيط على هذه الواجهة العامة.','Contact AssetVeyra':'تواصل مع AssetVeyra'
  },
  es: {
    'Market':'Mercado','Platform':'Plataforma','Workflow':'Flujo de trabajo','Sign in':'Iniciar sesión','Submit an asset':'Enviar un activo','Capital meets real assets.':'El capital se encuentra con los activos reales.','Explore the market':'Explorar el mercado','Investor workspace':'Espacio de trabajo del inversor','Real assets':'Activos reales','THE PLATFORM':'LA PLATAFORMA','TRANSACTION LIFECYCLE':'CICLO DE VIDA DE LA TRANSACCIÓN','Verification':'Verificación','Compliance':'Cumplimiento','Publication':'Publicación','Qualification':'Calificación','NDA':'Acuerdo de confidencialidad','Data Room':'Sala de datos','Diligence':'Due diligence','Offer':'Oferta','Negotiation':'Negociación','Contract':'Contrato','Closing':'Cierre','Security':'Seguridad','Privacy':'Privacidad','Terms':'Términos'
  },
  fr: {
    'Market':'Marché','Platform':'Plateforme','Workflow':'Flux de travail','Sign in':'Se connecter','Submit an asset':'Soumettre un actif','Capital meets real assets.':'Le capital rencontre les actifs réels.','Explore the market':'Explorer le marché','Investor workspace':'Espace de travail de l’investisseur','Real assets':'Actifs réels','THE PLATFORM':'LA PLATEFORME','TRANSACTION LIFECYCLE':'CYCLE DE VIE DE LA TRANSACTION','Verification':'Vérification','Compliance':'Conformité','Publication':'Publication','Qualification':'Qualification','NDA':'Accord de confidentialité','Data Room':'Data room','Diligence':'Due diligence','Offer':'Offre','Negotiation':'Négociation','Contract':'Contrat','Closing':'Clôture','Security':'Sécurité','Privacy':'Confidentialité','Terms':'Conditions'
  },
  zh: {
    'Market':'市场','Platform':'平台','Workflow':'工作流程','Sign in':'登录','Submit an asset':'提交资产','Capital meets real assets.':'资本连接真实资产。','Explore the market':'探索市场','Investor workspace':'投资者工作区','Real assets':'真实资产','THE PLATFORM':'平台','TRANSACTION LIFECYCLE':'交易生命周期','Verification':'验证','Compliance':'合规','Publication':'发布','Qualification':'资格审查','NDA':'保密协议','Data Room':'数据室','Diligence':'尽职调查','Offer':'报价','Negotiation':'谈判','Contract':'合同','Closing':'交割','Security':'安全','Privacy':'隐私','Terms':'条款'
  }
};

export function translateHome(text: string, locale: Locale): string {
  return HOME_TRANSLATIONS[locale][text] ?? text;
}
