import type { Locale } from '@/lib/i18n';

type TranslationSet = Record<Locale, string>;

export const TRUST_TRANSLATIONS: Record<string, TranslationSet> = {
  'trust.page.eyebrow': { en: 'TRUST & TRANSPARENCY', ar: 'الثقة والشفافية', zh: '信任与透明度', es: 'CONFIANZA Y TRANSPARENCIA', fr: 'CONFIANCE ET TRANSPARENCE' },
  'trust.page.title': { en: 'A clear process for serious transactions.', ar: 'عملية واضحة للمعاملات الجادة.', zh: '为严肃交易提供清晰流程。', es: 'Un proceso claro para operaciones serias.', fr: 'Un processus clair pour des transactions sérieuses.' },
  'trust.page.intro': { en: 'Kasab & Sons for Land and Real Estate Trading is an intermediary and transaction-coordination business. We connect parties, organize the process and coordinate professional support without holding the transaction funds.', ar: 'كساب وأبنائه لتجارة الأراضي والعقار جهة وساطة وتنسيق صفقات. نربط الأطراف وننظم العملية وننسق الدعم المهني دون حيازة أموال الصفقة.', zh: 'Kasab & Sons for Land and Real Estate Trading 提供中介与交易协调服务。我们连接交易各方、组织流程并协调专业支持，但不持有交易资金。', es: 'Kasab & Sons for Land and Real Estate Trading actúa como intermediario y coordinador de operaciones. Conectamos a las partes, organizamos el proceso y coordinamos apoyo profesional sin custodiar los fondos.', fr: 'Kasab & Sons for Land and Real Estate Trading agit comme intermédiaire et coordinateur de transactions. Nous mettons les parties en relation et coordonnons l’accompagnement professionnel sans détenir les fonds.' },
  'trust.model.title': { en: 'Our model', ar: 'نموذج عملنا', zh: '我们的模式', es: 'Nuestro modelo', fr: 'Notre modèle' },
  'trust.model.body': { en: 'We charge 1% of the final transaction value from the seller and 1% from the buyer when the transaction is completed, subject to a written agreement. We do not receive the purchase price or transaction deposits.', ar: 'نستحق عمولة بنسبة 1% من القيمة النهائية للصفقة من البائع و1% من المشتري عند إتمام الصفقة، وفق اتفاقية مكتوبة. ولا نستلم ثمن الشراء أو ودائع الصفقة.', zh: '交易完成后，我们根据书面协议分别向卖方和买方收取最终交易价值的 1%。我们不接收购买价款或交易押金。', es: 'Al completarse la operación, cobramos el 1% del valor final al vendedor y el 1% al comprador, conforme a un acuerdo escrito. No recibimos el precio de compra ni depósitos.', fr: 'À la conclusion de la transaction, nous facturons 1 % de la valeur finale au vendeur et 1 % à l’acheteur, selon un accord écrit. Nous ne recevons ni le prix d’achat ni les dépôts.' },
  'trust.no_guarantee': { en: 'We do not guarantee a sale, profit, financing or a particular outcome.', ar: 'لا نضمن البيع أو الربح أو التمويل أو أي نتيجة محددة.', zh: '我们不保证交易完成、利润、融资或任何特定结果。', es: 'No garantizamos la venta, los beneficios, la financiación ni un resultado concreto.', fr: 'Nous ne garantissons ni la vente, ni un bénéfice, ni un financement, ni un résultat particulier.' },
  'trust.no_funds': { en: 'We do not handle transaction funds. Payments are made directly through the agreed legal, banking or escrow process.', ar: 'لا نتعامل مع أموال الصفقة. تتم المدفوعات مباشرة عبر المسار القانوني أو المصرفي أو الضمان المتفق عليه.', zh: '我们不处理交易资金。付款通过约定的法律、银行或托管流程直接完成。', es: 'No gestionamos los fondos de la operación. Los pagos se realizan directamente mediante el proceso legal, bancario o de garantía acordado.', fr: 'Nous ne manipulons pas les fonds de la transaction. Les paiements sont effectués directement selon le processus juridique, bancaire ou séquestre convenu.' },
  'trust.people.title': { en: 'People and contact', ar: 'الأشخاص وبيانات التواصل', zh: '团队与联系方式', es: 'Personas y contacto', fr: 'Équipe et contact' },
  'trust.manager': { en: 'Manager: Bashar Kassab Al-Masaeed', ar: 'المدير: بشار كساب المساعيد', zh: '负责人：Bashar Kassab Al-Masaeed', es: 'Director: Bashar Kassab Al-Masaeed', fr: 'Directeur : Bashar Kassab Al-Masaeed' },
  'trust.legal_partner': { en: 'Legal partner: Mr. Tareq Al-Zyoud', ar: 'الشريك القانوني: الأستاذ طارق الزيود', zh: '法律合作伙伴：Tareq Al-Zyoud 先生', es: 'Socio legal: Sr. Tareq Al-Zyoud', fr: 'Partenaire juridique : Me Tareq Al-Zyoud' },
  'trust.contact': { en: 'General enquiries: info@assetveyra.com · +353 899 450 711', ar: 'للاستفسارات العامة: info@assetveyra.com · +353 899 450 711', zh: '一般咨询：info@assetveyra.com · +353 899 450 711', es: 'Consultas generales: info@assetveyra.com · +353 899 450 711', fr: 'Demandes générales : info@assetveyra.com · +353 899 450 711' },
  'trust.legal_notice': { en: 'The legal partner and professional providers act within their own professional scope. Each party may obtain independent legal, tax and financial advice.', ar: 'يعمل الشريك القانوني ومقدمو الخدمات المهنية ضمن نطاقهم المهني. ويجوز لكل طرف الحصول على استشارة قانونية وضريبية ومالية مستقلة.', zh: '法律合作伙伴及专业服务提供者在各自的专业范围内行事。各方均可获取独立的法律、税务和财务意见。', es: 'El socio legal y los proveedores profesionales actúan dentro de su propio ámbito. Cada parte puede obtener asesoramiento jurídico, fiscal y financiero independiente.', fr: 'Le partenaire juridique et les prestataires professionnels agissent dans leur propre périmètre. Chaque partie peut obtenir un conseil juridique, fiscal et financier indépendant.' },
  'how.page.eyebrow': { en: 'HOW WE WORK', ar: 'كيف نعمل', zh: '我们的流程', es: 'CÓMO TRABAJAMOS', fr: 'NOTRE FONCTIONNEMENT' },
  'how.page.title': { en: 'A controlled path from introduction to closing.', ar: 'مسار منضبط من التعارف حتى الإغلاق.', zh: '从介绍到交割的受控流程。', es: 'Un recorrido controlado desde la presentación hasta el cierre.', fr: 'Un parcours maîtrisé de la mise en relation à la clôture.' },
  'how.page.intro': { en: 'Each transaction follows an agreed process. Professional review, contracts and payment arrangements remain with the responsible legal, banking or escrow parties.', ar: 'تتبع كل معاملة عملية متفقًا عليها. وتبقى المراجعة المهنية والعقود وترتيبات الدفع لدى الجهات القانونية أو المصرفية أو جهات الضمان المسؤولة.', zh: '每笔交易都遵循约定流程。专业审查、合同和付款安排由负责的法律、银行或托管方处理。', es: 'Cada operación sigue un proceso acordado. La revisión profesional, los contratos y los pagos corresponden a las partes legales, bancarias o de garantía responsables.', fr: 'Chaque transaction suit un processus convenu. La revue professionnelle, les contrats et les paiements relèvent des parties juridiques, bancaires ou séquestres responsables.' },
  'how.1': { en: '1. Register the buyer or seller', ar: '1. تسجيل المشتري أو البائع', zh: '1. 注册买方或卖方', es: '1. Registrar al comprador o vendedor', fr: '1. Inscrire l’acheteur ou le vendeur' },
  'how.2': { en: '2. Complete identity and information checks', ar: '2. استكمال التحقق من الهوية والبيانات', zh: '2. 完成身份和信息核查', es: '2. Completar las verificaciones de identidad e información', fr: '2. Effectuer les vérifications d’identité et d’informations' },
  'how.3': { en: '3. Sign a written brokerage agreement', ar: '3. توقيع اتفاقية وساطة مكتوبة', zh: '3. 签署书面中介协议', es: '3. Firmar un acuerdo de intermediación por escrito', fr: '3. Signer un accord d’intermédiation écrit' },
  'how.4': { en: '4. Review the asset and available documents', ar: '4. مراجعة الأصل والوثائق المتاحة', zh: '4. 审查资产及可用文件', es: '4. Revisar el activo y los documentos disponibles', fr: '4. Examiner l’actif et les documents disponibles' },
  'how.5': { en: '5. Coordinate legal review and the agreed closing route', ar: '5. تنسيق المراجعة القانونية ومسار الإغلاق المتفق عليه', zh: '5. 协调法律审查及约定的交割路径', es: '5. Coordinar la revisión legal y la vía de cierre acordada', fr: '5. Coordonner la revue juridique et le processus de clôture convenu' },
  'how.6': { en: '6. Coordinate communication and negotiation', ar: '6. تنسيق التواصل والتفاوض', zh: '6. 协调沟通与谈判', es: '6. Coordinar la comunicación y la negociación', fr: '6. Coordonner les échanges et la négociation' },
  'how.7': { en: '7. Sign contracts and transfer funds through the agreed process', ar: '7. توقيع العقود وتحويل الأموال عبر المسار المتفق عليه', zh: '7. 签署合同并通过约定流程转移资金', es: '7. Firmar los contratos y transferir los fondos mediante el proceso acordado', fr: '7. Signer les contrats et transférer les fonds selon le processus convenu' },
  'how.8': { en: '8. Complete closing and archive the transaction record', ar: '8. إتمام الإغلاق وأرشفة سجل المعاملة', zh: '8. 完成交割并归档交易记录', es: '8. Completar el cierre y archivar el expediente', fr: '8. Finaliser la clôture et archiver le dossier' },
  'how.costs': { en: 'Legal, travel, government and other third-party costs are paid by the party responsible for them under the applicable agreement.', ar: 'يدفع كل طرف الأتعاب القانونية وتكاليف السفر والرسوم الحكومية والمصاريف الأخرى المسندة إليه بموجب الاتفاق المعمول به.', zh: '法律、旅行、政府及其他第三方费用由适用协议中负责的一方承担。', es: 'Los costes legales, de viaje, gubernamentales y de terceros corresponden a la parte responsable conforme al acuerdo aplicable.', fr: 'Les frais juridiques, de voyage, gouvernementaux et autres frais de tiers sont supportés par la partie responsable selon l’accord applicable.' },
};
