import { translate, type Locale } from '@/lib/i18n';

export const EXTENDED_LOCALES = ['en','ar','es','fr','de','pt'] as const;
// Keep the legacy Locale type for compatibility with existing non-RC surfaces.
// German and Portuguese are runtime-supported extended locales and are normalized/cast at the boundary.
export type ExtendedLocale = Locale;
export const EXTENDED_LOCALE_LABELS: Record<string,string> = { en:'English', ar:'العربية', es:'Español', fr:'Français', de:'Deutsch', pt:'Português' };
export const EXTENDED_RTL_LOCALES = new Set<string>(['ar']);

const RC_TRANSLATIONS: Record<string, Partial<Record<'de'|'pt', string>>> = {
  'Country':{de:'Land',pt:'País'}, 'Region / State / Province':{de:'Region / Bundesland / Provinz',pt:'Região / Estado / Província'}, 'Private address / location description':{de:'Private Adresse / Standortbeschreibung',pt:'Endereço privado / descrição da localização'},
  'Latitude':{de:'Breitengrad',pt:'Latitude'}, 'Longitude':{de:'Längengrad',pt:'Longitude'}, 'Use my current location':{de:'Meinen aktuellen Standort verwenden',pt:'Usar minha localização atual'},
  'Location could not be detected. Enter coordinates manually.':{de:'Standort konnte nicht ermittelt werden. Koordinaten manuell eingeben.',pt:'Não foi possível detectar a localização. Insira as coordenadas manualmente.'}, 'Map preview. Coordinates remain the canonical location values.':{de:'Kartenvorschau. Die Koordinaten bleiben die maßgeblichen Standortwerte.',pt:'Pré-visualização do mapa. As coordenadas permanecem como valores canônicos da localização.'}, 'Location map preview':{de:'Kartenvorschau des Standorts',pt:'Pré-visualização do mapa da localização'}, 'Enter latitude and longitude to preview the selected location.':{de:'Geben Sie Breiten- und Längengrad ein, um den ausgewählten Standort anzuzeigen.',pt:'Insira latitude e longitude para visualizar a localização selecionada.'},
  'BASIC INFORMATION':{de:'GRUNDINFORMATIONEN',pt:'INFORMAÇÕES BÁSICAS'}, 'LOCATION':{de:'STANDORT',pt:'LOCALIZAÇÃO'}, 'PRICING':{de:'PREISE',pt:'PREÇOS'}, 'PROPERTY DETAILS':{de:'IMMOBILIENDETAILS',pt:'DETALHES DO IMÓVEL'}, 'MEDIA':{de:'MEDIEN',pt:'MÍDIA'}, 'PREVIEW':{de:'VORSCHAU',pt:'PRÉ-VISUALIZAÇÃO'},
  'Create listing':{de:'Inserat erstellen',pt:'Criar anúncio'}, 'Create a complete property record. Submission enters verification and is not published automatically.':{de:'Erstellen Sie einen vollständigen Immobiliendatensatz. Die Einreichung wird zuerst geprüft und nicht automatisch veröffentlicht.',pt:'Crie um registro completo do imóvel. O envio entra na verificação e não é publicado automaticamente.'}, 'Images are optional, but every selected image must upload successfully before submission is reported successful.':{de:'Bilder sind optional, aber jedes ausgewählte Bild muss erfolgreich hochgeladen werden, bevor die Einreichung als erfolgreich gilt.',pt:'As imagens são opcionais, mas todas as imagens selecionadas devem ser enviadas com sucesso antes que o envio seja considerado concluído.'},
  'Asset title':{de:'Objekttitel',pt:'Título do imóvel'}, 'Asset type':{de:'Objekttyp',pt:'Tipo de imóvel'}, 'Public summary':{de:'Öffentliche Zusammenfassung',pt:'Resumo público'}, 'Area m²':{de:'Fläche m²',pt:'Área m²'}, 'Currency':{de:'Währung',pt:'Moeda'}, 'Asking price':{de:'Angebotspreis',pt:'Preço pedido'}, 'Submit Asset for Verification':{de:'Objekt zur Prüfung einreichen',pt:'Enviar imóvel para verificação'}, 'Property subtype':{de:'Immobilien-Untertyp',pt:'Subtipo do imóvel'}, 'Full description':{de:'Vollständige Beschreibung',pt:'Descrição completa'},
  'Transaction type':{de:'Transaktionsart',pt:'Tipo de transação'}, 'Negotiable':{de:'Verhandelbar',pt:'Negociável'}, 'Not specified':{de:'Nicht angegeben',pt:'Não especificado'}, 'Yes':{de:'Ja',pt:'Sim'}, 'No':{de:'Nein',pt:'Não'}, 'Sale':{de:'Verkauf',pt:'Venda'}, 'Lease':{de:'Vermietung',pt:'Locação'}, 'Sale or lease':{de:'Verkauf oder Vermietung',pt:'Venda ou locação'},
  'LIVE PREVIEW':{de:'LIVE-VORSCHAU',pt:'PRÉ-VISUALIZAÇÃO AO VIVO'}, 'Listing title':{de:'Inseratstitel',pt:'Título do anúncio'}, 'Main image':{de:'Hauptbild',pt:'Imagem principal'}, 'Gallery image':{de:'Galeriebild',pt:'Imagem da galeria'}, 'No images selected yet.':{de:'Noch keine Bilder ausgewählt.',pt:'Nenhuma imagem selecionada.'}, 'Your public summary will appear here.':{de:'Ihre öffentliche Zusammenfassung wird hier angezeigt.',pt:'Seu resumo público aparecerá aqui.'}, 'This preview uses the same submitted data model. Publication remains controlled by verification and compliance.':{de:'Diese Vorschau verwendet dasselbe Datenmodell wie die Einreichung. Die Veröffentlichung bleibt durch Prüfung und Compliance kontrolliert.',pt:'Esta pré-visualização usa o mesmo modelo de dados enviado. A publicação continua sujeita à verificação e conformidade.'},
  'Property images':{de:'Immobilienbilder',pt:'Imagens do imóvel'}, 'Up to 20 images. The first image is the main image. Images are compressed before upload.':{de:'Bis zu 20 Bilder. Das erste Bild ist das Hauptbild. Die Bilder werden vor dem Upload komprimiert.',pt:'Até 20 imagens. A primeira imagem é a principal. As imagens são comprimidas antes do envio.'}, 'Preparing images…':{de:'Bilder werden vorbereitet…',pt:'Preparando imagens…'}, '20 images maximum.':{de:'Maximal 20 Bilder.',pt:'Máximo de 20 imagens.'}, 'This image could not be prepared.':{de:'Dieses Bild konnte nicht vorbereitet werden.',pt:'Não foi possível preparar esta imagem.'}, 'Error':{de:'Fehler',pt:'Erro'}, 'Up':{de:'Nach oben',pt:'Subir'}, 'Down':{de:'Nach unten',pt:'Descer'}, 'Remove':{de:'Entfernen',pt:'Remover'},
  'Land':{de:'Grundstück',pt:'Terreno'}, 'Agricultural land':{de:'Landwirtschaftliche Fläche',pt:'Terreno agrícola'}, 'Development land':{de:'Bauland',pt:'Terreno para desenvolvimento'}, 'Villa':{de:'Villa',pt:'Villa'}, 'House':{de:'Haus',pt:'Casa'}, 'Palace':{de:'Palast',pt:'Palácio'}, 'Apartment':{de:'Wohnung',pt:'Apartamento'}, 'Residential building':{de:'Wohngebäude',pt:'Edifício residencial'}, 'Commercial':{de:'Gewerbe',pt:'Comercial'}, 'Office':{de:'Büro',pt:'Escritório'}, 'Retail':{de:'Einzelhandel',pt:'Varejo'}, 'Hotel':{de:'Hotel',pt:'Hotel'}, 'Resort':{de:'Resort',pt:'Resort'}, 'Apart-hotel':{de:'Aparthotel',pt:'Apart-hotel'}, 'Hospitality':{de:'Gastgewerbe',pt:'Hospitalidade'}, 'Industrial':{de:'Industrie',pt:'Industrial'}, 'Mixed use':{de:'Mischnutzung',pt:'Uso misto'}, 'Development project':{de:'Entwicklungsprojekt',pt:'Projeto de desenvolvimento'}, 'Infrastructure':{de:'Infrastruktur',pt:'Infraestrutura'}, 'Renewable energy':{de:'Erneuerbare Energie',pt:'Energia renovável'}, 'Other':{de:'Sonstiges',pt:'Outro'},
  'Building area m²':{de:'Gebäudefläche m²',pt:'Área construída m²'}, 'Land area m²':{de:'Grundstücksfläche m²',pt:'Área do terreno m²'}, 'Bedrooms':{de:'Schlafzimmer',pt:'Quartos'}, 'Bathrooms':{de:'Badezimmer',pt:'Banheiros'}, 'Floors':{de:'Etagen',pt:'Andares'}, 'Floor number':{de:'Etage',pt:'Número do andar'}, 'Total floors':{de:'Gesamtetagen',pt:'Total de andares'}, 'Parking spaces':{de:'Stellplätze',pt:'Vagas de estacionamento'}, 'Pool':{de:'Pool',pt:'Piscina'}, 'Garden':{de:'Garten',pt:'Jardim'}, 'Furnished':{de:'Möbliert',pt:'Mobiliado'}, 'Balcony':{de:'Balkon',pt:'Varanda'}, 'Rooms':{de:'Zimmer',pt:'Quartos'}, 'Suites':{de:'Suiten',pt:'Suítes'}, 'Restaurants':{de:'Restaurants',pt:'Restaurantes'}, 'Conference facilities':{de:'Konferenzeinrichtungen',pt:'Instalações para conferências'}, 'Classification':{de:'Klassifizierung',pt:'Classificação'}, 'Operating status':{de:'Betriebsstatus',pt:'Status operacional'}, 'Occupancy %':{de:'Auslastung %',pt:'Ocupação %'}, 'Facilities':{de:'Einrichtungen',pt:'Instalações'}, 'Units':{de:'Einheiten',pt:'Unidades'}, 'Current use':{de:'Aktuelle Nutzung',pt:'Uso atual'}, 'Condition':{de:'Zustand',pt:'Condição'}, 'Construction year':{de:'Baujahr',pt:'Ano de construção'}, 'Amenities':{de:'Ausstattung',pt:'Comodidades'}, 'Land use':{de:'Landnutzung',pt:'Uso do terreno'}, 'Zoning':{de:'Widmung / Zonierung',pt:'Zoneamento'}, 'Development potential':{de:'Entwicklungspotenzial',pt:'Potencial de desenvolvimento'}, 'Road access':{de:'Straßenzugang',pt:'Acesso rodoviário'}, 'Utilities':{de:'Versorgung',pt:'Infraestrutura de serviços'}, 'Water':{de:'Wasser',pt:'Água'}, 'Electricity':{de:'Strom',pt:'Eletricidade'}, 'Sewage':{de:'Abwasser',pt:'Esgoto'}, 'Gas':{de:'Gas',pt:'Gás'}, 'Telecom':{de:'Telekommunikation',pt:'Telecomunicações'}, 'Frontage m':{de:'Frontbreite m',pt:'Testada m'}, 'Topography':{de:'Topografie',pt:'Topografia'}, 'Development status':{de:'Entwicklungsstatus',pt:'Status de desenvolvimento'}, 'Permitted use':{de:'Zulässige Nutzung',pt:'Uso permitido'}, 'Planned units':{de:'Geplante Einheiten',pt:'Unidades planejadas'}, 'Planned area m²':{de:'Geplante Fläche m²',pt:'Área planejada m²'}, 'Additional rooms':{de:'Zusätzliche Räume',pt:'Cômodos adicionais'},
  'New':{de:'Neu',pt:'Novo'}, 'Excellent':{de:'Ausgezeichnet',pt:'Excelente'}, 'Good':{de:'Gut',pt:'Bom'}, 'Fair':{de:'Ordentlich',pt:'Regular'}, 'Needs renovation':{de:'Renovierungsbedürftig',pt:'Precisa de reforma'}, 'Under construction':{de:'Im Bau',pt:'Em construção'}, 'Residential':{de:'Wohnen',pt:'Residencial'}, 'Agricultural':{de:'Landwirtschaftlich',pt:'Agrícola'}, 'Recreational':{de:'Freizeit',pt:'Recreativo'}, 'Institutional':{de:'Institutionell',pt:'Institucional'}, 'Direct':{de:'Direkt',pt:'Direto'}, 'Shared':{de:'Gemeinsam',pt:'Compartilhado'}, 'Planned':{de:'Geplant',pt:'Planejado'}, 'None':{de:'Keine',pt:'Nenhuma'}, 'Unknown':{de:'Unbekannt',pt:'Desconhecido'}, 'Flat':{de:'Flach',pt:'Plano'}, 'Sloped':{de:'Hanglage',pt:'Inclinado'}, 'Hilly':{de:'Hügelig',pt:'Acidentado'}, 'Mixed':{de:'Gemischt',pt:'Misto'}, 'Raw':{de:'Unerschlossen',pt:'Bruto'}, 'Concept':{de:'Konzept',pt:'Conceito'}, 'Permitted':{de:'Genehmigt',pt:'Aprovado'}, 'Serviced':{de:'Erschlossen',pt:'Com infraestrutura'}, 'Under development':{de:'In Entwicklung',pt:'Em desenvolvimento'}, 'Operating':{de:'In Betrieb',pt:'Em operação'}, 'Closed':{de:'Geschlossen',pt:'Fechado'}, 'Under renovation':{de:'In Renovierung',pt:'Em reforma'},
  'No additional property details are available.':{de:'Keine zusätzlichen Immobiliendetails verfügbar.',pt:'Não há detalhes adicionais do imóvel disponíveis.'}, 'PUBLISHED OPPORTUNITY · CONTROLLED ACCESS':{de:'VERÖFFENTLICHTE GELEGENHEIT · KONTROLLIERTER ZUGANG',pt:'OPORTUNIDADE PUBLICADA · ACESSO CONTROLADO'}, 'Overview':{de:'Übersicht',pt:'Visão geral'}, 'Minimum ticket':{de:'Mindestinvestment',pt:'Investimento mínimo'}, 'Target return':{de:'Zielrendite',pt:'Retorno alvo'}, 'INVESTMENT THESIS':{de:'INVESTMENTTHESE',pt:'TESE DE INVESTIMENTO'}, 'TRANSACTION STRUCTURE':{de:'TRANSAKTIONSSTRUKTUR',pt:'ESTRUTURA DA TRANSAÇÃO'}, 'Additional investment thesis information is available subject to the applicable access level.':{de:'Weitere Informationen zur Investmentthese sind abhängig von der jeweiligen Zugriffsebene verfügbar.',pt:'Informações adicionais sobre a tese de investimento estão disponíveis conforme o nível de acesso aplicável.'}, 'Transaction structure details are provided during qualification and transaction review.':{de:'Details zur Transaktionsstruktur werden während Qualifizierung und Transaktionsprüfung bereitgestellt.',pt:'Os detalhes da estrutura da transação são fornecidos durante a qualificação e revisão da transação.'}, 'TRANSACTION PATH':{de:'TRANSAKTIONSPFAD',pt:'CAMINHO DA TRANSAÇÃO'}, 'Interest':{de:'Interesse',pt:'Interesse'}, 'Qualify':{de:'Qualifizieren',pt:'Qualificar'}, 'NDA':{de:'Vertraulichkeitsvereinbarung',pt:'NDA'}, 'Data Room':{de:'Datenraum',pt:'Sala de dados'}, 'Due Diligence':{de:'Due-Diligence-Prüfung',pt:'Due diligence'}, 'Offer':{de:'Angebot',pt:'Oferta'}, 'INVESTOR ACCESS':{de:'INVESTORZUGANG',pt:'ACESSO DO INVESTIDOR'}, 'Register qualified interest':{de:'Qualifiziertes Interesse registrieren',pt:'Registrar interesse qualificado'}, 'Register interest':{de:'Interesse registrieren',pt:'Registrar interesse'}, 'Marketplace':{de:'Marktplatz',pt:'Marketplace'}, 'Sign out':{de:'Abmelden',pt:'Sair'},
  'property_description_required':{de:'Eine vollständige Objektbeschreibung ist erforderlich.',pt:'É necessária uma descrição completa do imóvel.'}, 'property_details_required':{de:'Immobiliendetails sind erforderlich.',pt:'Os detalhes do imóvel são obrigatórios.'}, 'invalid_property_details':{de:'Die Immobiliendetails sind ungültig.',pt:'Os detalhes do imóvel são inválidos.'}, 'property_subtype_mismatch':{de:'Der Untertyp passt nicht zum Immobilientyp.',pt:'O subtipo não corresponde ao tipo de imóvel.'}, 'Invalid asset type.':{de:'Ungültiger Immobilientyp.',pt:'Tipo de imóvel inválido.'}, 'Validation failed. Please review the highlighted fields.':{de:'Die Validierung ist fehlgeschlagen. Bitte prüfen Sie die markierten Felder.',pt:'A validação falhou. Revise os campos destacados.'}
};

export function normalizeExtendedLocale(value: string): ExtendedLocale { const normalized = value.toLowerCase().split('-')[0]; return (EXTENDED_LOCALES as readonly string[]).includes(normalized) ? normalized as ExtendedLocale : 'en'; }
export function detectExtendedLocaleFromLanguages(languages: string[]): ExtendedLocale { for (const language of languages) { const normalized = normalizeExtendedLocale(language); if (normalized !== 'en' || language.toLowerCase().startsWith('en')) return normalized; } return 'en'; }
export function translateExtended(key: string, locale: ExtendedLocale): string { if (locale === ('de' as ExtendedLocale) || locale === ('pt' as ExtendedLocale)) return RC_TRANSLATIONS[key]?.[locale as 'de'|'pt'] ?? translate(key, 'en' as Locale); return translate(key, locale as Locale); }
