import { z } from 'zod';

const n = z.number().finite().nonnegative();
const s = (max: number) => z.string().trim().max(max);
const common = z.object({ condition: z.enum(['new','excellent','good','fair','needs_renovation','under_construction']).optional(), construction_year: z.number().int().min(1000).max(new Date().getFullYear()+2).optional(), furnished: z.boolean().optional(), parking_spaces: n.int().max(10000).optional(), total_floors: n.int().max(10000).optional(), floor_number: z.number().int().min(-10).max(10000).optional(), amenities: z.array(s(120)).max(50).optional(), description: s(12000).optional(), transaction_type: z.enum(['sale','lease','sale_or_lease']).optional(), negotiable: z.boolean().optional() }).strict();
const land = z.object({ land_area_sqm:n.optional(), land_use:z.enum(['residential','commercial','agricultural','industrial','mixed_use','recreational','institutional','other']).optional(), zoning:s(160).optional(), development_potential:s(1000).optional(), road_access:z.enum(['direct','shared','planned','none','unknown']).optional(), utilities:z.array(z.enum(['water','electricity','sewage','gas','telecom'])).max(5).optional(), water:z.boolean().optional(), electricity:z.boolean().optional(), sewage:z.boolean().optional(), frontage_m:n.optional(), topography:z.enum(['flat','sloped','hilly','mixed','unknown']).optional(), development_status:z.enum(['raw','planned','permitted','under_development','serviced']).optional() }).strict();
const residential = z.object({ building_area_sqm:n.optional(), land_area_sqm:n.optional(), bedrooms:n.int().max(1000).optional(), bathrooms:n.max(1000).optional(), floors:n.int().max(1000).optional(), parking_spaces:n.int().max(1000).optional(), pool:z.boolean().optional(), garden:z.boolean().optional(), furnished:z.boolean().optional(), condition:common.shape.condition, construction_year:common.shape.construction_year, additional_rooms:z.array(s(120)).max(30).optional(), amenities:z.array(s(120)).max(50).optional() }).strict();
const apartment = z.object({ building_area_sqm:n.optional(), bedrooms:n.int().max(1000).optional(), bathrooms:n.max(1000).optional(), floor_number:z.number().int().min(-10).max(10000).optional(), total_floors:n.int().max(10000).optional(), parking_spaces:n.int().max(1000).optional(), balcony:z.boolean().optional(), furnished:z.boolean().optional(), condition:common.shape.condition, construction_year:common.shape.construction_year, amenities:z.array(s(120)).max(50).optional() }).strict();
const hospitality = z.object({ land_area_sqm:n.optional(), building_area_sqm:n.optional(), rooms:n.int().max(100000).optional(), suites:n.int().max(100000).optional(), floors:n.int().max(10000).optional(), restaurants:n.int().max(1000).optional(), conference_facilities:z.boolean().optional(), pool:z.boolean().optional(), parking_spaces:n.int().max(100000).optional(), classification:s(80).optional(), operating_status:z.enum(['operating','closed','under_renovation','under_construction','planned']).optional(), occupancy:n.min(0).max(100).optional(), facilities:z.array(s(120)).max(80).optional() }).strict();
const commercial = z.object({ building_area_sqm:n.optional(), units:n.int().max(100000).optional(), floors:n.int().max(10000).optional(), occupancy:n.min(0).max(100).optional(), current_use:s(500).optional(), rental_income:n.optional(), parking_spaces:n.int().max(100000).optional(), condition:common.shape.condition, amenities:z.array(s(120)).max(50).optional() }).strict();
const development = z.object({ development_status:z.enum(['concept','planned','permitted','under_construction','completed']).optional(), permitted_use:s(300).optional(), planned_units:n.int().max(1000000).optional(), planned_area_sqm:n.optional(), development_potential:s(1000).optional(), zoning:s(160).optional(), utilities:z.array(z.enum(['water','electricity','sewage','gas','telecom'])).max(5).optional() }).strict();
const empty=z.object({}).strict();
const branch=(subtype:string,specific:z.ZodTypeAny)=>z.object({subtype:z.literal(subtype),common:common.default({}),details:specific.default({})}).strict();
export const propertyDetailsSchema=z.discriminatedUnion('subtype',[
 branch('land',land),branch('agricultural_land',land),branch('development_land',land),branch('villa',residential),branch('house',residential),branch('palace',residential),branch('residential_building',residential),branch('apartment',apartment),branch('commercial',commercial),branch('office',commercial),branch('retail',commercial),branch('hotel',hospitality),branch('resort',hospitality),branch('apart_hotel',hospitality),branch('hospitality',hospitality),branch('industrial',commercial),branch('mixed_use',commercial),branch('development',development),branch('infrastructure',development),branch('renewable_energy',development),branch('other',empty)
]);
export type PropertyDetails=z.infer<typeof propertyDetailsSchema>;
export const ASSET_SUBTYPES={land:['land','agricultural_land','development_land'],residential:['villa','house','palace','apartment','residential_building'],commercial:['commercial','office','retail'],hotel:['hotel'],hospitality:['resort','apart_hotel','hospitality'],industrial:['industrial'],mixed_use:['mixed_use'],development_project:['development'],infrastructure:['infrastructure'],renewable_energy:['renewable_energy'],other:['other']} as const;
export function parsePropertyDetails(raw:FormDataEntryValue|null,assetType:string):PropertyDetails{if(typeof raw!=='string'||!raw.trim())throw new Error('property_details_required');let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error('invalid_property_details')}const parsed=propertyDetailsSchema.parse(value);const allowed=(ASSET_SUBTYPES as Record<string,readonly string[]>)[assetType];if(!allowed?.includes(parsed.subtype))throw new Error('property_subtype_mismatch');return parsed;}
